# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class SofifaItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    Name = scrapy.Field()
    Positions = scrapy.Field()
    Registred_Positions = scrapy.Field()
    Rating = scrapy.Field()
    Potential_Rating = scrapy.Field()
    Injury_Tolerance = scrapy.Field()
    Foot = scrapy.Field()
    Attack = scrapy.Field()
    Defence = scrapy.Field()
    Balance = scrapy.Field()
    Stamina = scrapy.Field()
    Speed = scrapy.Field()
    Acceleration = scrapy.Field()
    Response = scrapy.Field()
    Agility = scrapy.Field()
    Dribble_Accuracy = scrapy.Field()
    Dribble_Speed = scrapy.Field()
    Short_Pass_Accuracy = scrapy.Field()
    Short_Pass_Speed = scrapy.Field()
    Long_Pass_Accuracy = scrapy.Field()
    Long_Pass_Speed = scrapy.Field()
    Shot_Accuracy = scrapy.Field()
    Shot_Power = scrapy.Field()
    Shot_Technique = scrapy.Field()
    Free_Kick_Accuracy = scrapy.Field()
    Swerve = scrapy.Field()
    Heading = scrapy.Field()
    Jump = scrapy.Field()
    Technique = scrapy.Field()
    Aggression = scrapy.Field()
    Mentality = scrapy.Field()
    GK_Skills = scrapy.Field()
    Team_work = scrapy.Field()
    Condition_Fitness = scrapy.Field()
    Spec_Dribbling = scrapy.Field()
    Spec_Tactical_Dribble = scrapy.Field()
    Spec_Positioning = scrapy.Field()
    Spec_Reaction = scrapy.Field()
    Spec_Playmaking = scrapy.Field()
    Spec_Passing = scrapy.Field()
    Spec_Scoring = scrapy.Field()
    Spec_1_1_Scoring = scrapy.Field()
    Spec_Post_Player = scrapy.Field()
    Spec_Lines = scrapy.Field()
    Spec_Middle_Shooting = scrapy.Field()
    Spec_Penalties = scrapy.Field()
    Spec_1_Touch_Pass = scrapy.Field()
    Spec_Outside = scrapy.Field()
    Spec_Marking = scrapy.Field()
    Spec_Sliding = scrapy.Field()
    Spec_Covering = scrapy.Field()
    Spec_D_Line_Control = scrapy.Field()
    Spec_Penalty_Stopper = scrapy.Field()
    Spec_1_On_1_Stopper = scrapy.Field()
    Spec_Long_Throw = scrapy.Field()
    Injury_Tolerance = scrapy.Field()

